name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/setup-python@v2
     - name: Setup GCC
       run:   |
          sudo apt update
          sudo apt install g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10
          sudo update-alternatives --config gcc
     - uses: actions/checkout@v2
       with:
         repository: 'wotpp/wotpp'
         ref: 'master'
     - uses: BSFishy/meson-build@v1.0.2
       with:
         action: build
         directory: 'build'
         setup-options: --buildtype=release -Ddisable_run=false
     - run:   |
         ninja -C build test
         sudo pip3 install ninja
         sudo ninja -C build install
     - uses: actions/checkout@v2
     - uses: textbook/git-checkout-submodule-action@master
     - run: make
     - uses: JamesIves/github-pages-deploy-action@4.1.3
       with:
         branch: gh-pages
         folder: html

